# Generated by Django 4.2.16 on 2024-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiaataapp', '0002_address_cart_order_product_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
