# Generated by Django 4.2.16 on 2024-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiaataapp', '0005_rename_postal_code_address_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hotel_image',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
